name: Deploy Doc Website
on:
  push:
    branches:
      - main

jobs:
  main-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@latest

      - name: Install dependencies
        run: npm i

      - name: Build Demo
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
